# Generated by Django 4.0.6 on 2022-07-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_pokemonentity_health_pokemonentity_stamina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='Defence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
